#+STARTUP: content logdone hideblocks
#+TODO: TASK(t!) | DONE(d) CANCEL(c)
#+TODO: BUG(b!) | FIXED(f) REJECT(r)
#+PRIORITIES: A F C
#+TAGS: current(c) testing(t)
#+CONSTANTS: last_issue_id=28

* Задачи
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив задач
  :END:

** TASK При наведении на значки сделать всплывающие подсказки
   :PROPERTIES:
   :issue_id: 7
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Иногда непонятно, что обозначает значок. Поэтому при наведении на
   него должна всплывать подсказка.

** TASK Сделать popup с информацией о версии
   :PROPERTIES:
   :issue_id: 8
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   В popup должно быть несколько фреймов. Первый - информационный,
   возможно, с картинкой приложения. Второй - с кнопками для
   функций. Переход между фреймами выполняется по кнопке внизу фрейма.

   В popup должна быть кнопка help на видном месте, которая открывает
   вкладку с подробной помощью по использованию расширения. В
   открывшейся вкладке может быть подробное описание с картинками.

   В popup должны быть радио-кнопки для переключения страниц. Текущая
   страница должна подсвечивать свою радиокнопку. Также должна быть
   кнопка next.

** TASK Перенести кнопки из lowes в popup
   :PROPERTIES:
   :issue_id: 9
   :issue_type: task
   :END:

   [2019-06-22 Сб]

** TASK Сделать раскраску найденных подстрок в сообщении
   :PROPERTIES:
   :issue_id: 10
   :issue_type: task
   :END:

   [2019-06-22 Сб]

** TASK Придумать слежение за показателями
   :PROPERTIES:
   :issue_id: 11
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Понятие показателей абстрактно. Это могут быть лайки, одобрения или
   что-то ещё.

   С момента последней проверки показателей можно при новой проверке
   показателей брать разницу в их значениях и, если есть изменения,
   выводить эту разницу куда-нибудь для привлечения внимания к
   изменению показателей.

** TASK Сделать экспорт и импорт настроек расширения
   :PROPERTIES:
   :issue_id: 12
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Если настроек становится много, то иногда их надо сохранить за
   пределами браузера и иметь возможность быстро восстановить обратно.

   Формат должен быть JSON, чтобы его легко было редактировать и
   генерировать другими программами.

** TASK Сделать локализацию для разных языков
   :PROPERTIES:
   :issue_id: 13
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Нужен английский и русский. И нужна кнопка переключения на тот или
   другой язык. Эта кнопка должна быть в popup.

** TASK Прочитать из новой версии что-нибудь в авторизованном режиме
   :PROPERTIES:
   :issue_id: 16
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Так как авторизация затруднена слишком сложным механизмом, нужно
   просто заходить в авторизованном режиме на страницу новой версии в
   браузере и раширение должно скачивать себе доступную информацию,
   если обнаруживает, что авторизация пройдена. При этом на новой
   версии всё отмечается прочитанным, а использование информации
   происходит уже в старой версии.

** TASK Сделать чтение новых ответов с выводом счётчика в popup
   :PROPERTIES:
   :issue_id: 17
   :issue_type: task
   :END:

   [2019-06-22 Сб]

    Сообщения-ответы читаются в новой версии форума и пишутся сверху в
    старой версии форума.

    Каждое сообщение-ответ содержит ссылку и кнопку закрытия. Закрытие
    сообщения-ответа приводит к его закрытию в новой версии форума.

** TASK Сделать просмотр своих сообщений с выводом лайков на них
   :PROPERTIES:
   :issue_id: 18
   :issue_type: task
   :END:

   [2019-06-22 Сб]

   Сообщения читаются в новой версии форума и пишутся сверху в старой
   версии форума.

   В настройках должно быть поле максимального количества сообщений.

** TASK Сделать правильную обработку видео YouTube
   :PROPERTIES:
   :issue_id: 21
   :issue_type: task
   :END:

   [2020-08-12 Ср]

   Сейчас на Афише некоторые видео стали публиковать на сервисе
   YouTube. Поэтому надо либо не трогать их, либо вставлять ролик в
   тег video, как это делается с другими видео.

** TASK Сделать popup при нажатии на значок расширения
   :PROPERTIES:
   :issue_id: 25
   :issue_type: task
   :END:

   [2020-08-12 Ср]

   Сейчас при нажатии на значок ничего не происходит. Нужно сделать
   так, чтобы при нажатии выпадала большая картинка расширения и
   информация о названии расширения, версии расширения, авторе
   расширения.

** TASK Сделать возможность видимости даты создания ника возле него
   :PROPERTIES:
   :issue_id: 27
   :issue_type: task
   :END:

   [2020-08-12 Ср]

   Сейчас, когда ник пишет что-то, неясно, сколько времени он на
   форуме и нужно заглядывать в его информацию. Иногда таких ников так
   много, что заглядывать и запоминать их становится проблематично.

   Нужен индикатор возле ника, по которому сразу видно, кто на форуме
   давно, а кто зарегистрировался совсем недавно. Так переполненные и
   очень активные темы будут читаться гораздо быстрее и определённее.

** TASK Установить в браузере признак выполненного открытия нового форума
   :PROPERTIES:
   :issue_id: 28
   :issue_type: task
   :END:

   [2020-08-12 Ср]

   Сейчас для отображения лайков с новой версии форума нужно сначала
   нажать на кнопку перехода на новую версию, чтобы получить в браузер
   какую-то информацию (вероятно, печенье) о событии перехода на новую
   версию форума. После этого нажатия лайки начинают появляться.

   Нужно устанавливать требуемую информацию в браузер сразу, без
   нажатия кнопки.


* Баги
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив багов
  :END:

** BUG Исправить перенос кнопки лайков в верхнем сообщении топика
   :PROPERTIES:
   :issue_id: 19
   :issue_type: bug
   :END:

   [2019-06-22 Сб]

   https://forum.sakh.com/?sub=1775470

** BUG Исправить замену видео в закрытом ролике
   :PROPERTIES:
   :issue_id: 20
   :issue_type: bug
   :END:

   [2019-06-22 Сб]

   https://sakhalin.tv/movie/94978/

** BUG Исправить прямое присваивание кода HTML
   :PROPERTIES:
   :issue_id: 26
   :issue_type: bug
   :END:

   [2020-08-12 Ср]

   При подписывании расширения на сайте Mozilla анализатор сообщает,
   что в коде есть небезопасные места, в которых происходит прямое
   присваивание текста в виде HTML.

   На первый взгляд эти места кажутся безопасными, но, видимо,
   существует какой-то более правильный способ выполнить аналогичное
   действие. Нужно его узнать и переделать все неправильные
   присваивания в правильные.


* Окружение проекта
  :PROPERTIES:
  :COLUMNS:  %3issue_id(ID) %4issue_type(TYPE) %TODO %40ITEM %SCHEDULED %DEADLINE %1PRIORITY
  :ARCHIVE:  tasks_archive.org::* Архив окружения
  :END:

** TASK Сделать основу для юнит-тестов
   :PROPERTIES:
   :issue_id: 14
   :issue_type: task
   :END:

   [2019-06-22 Сб]

** TASK Сделать репозиторий
   :PROPERTIES:
   :issue_id: 15
   :issue_type: task
   :END:

   [2019-06-22 Сб]

** TASK Сделать более подробное описание расширения внутри README
   :PROPERTIES:
   :issue_id: 22
   :issue_type: task
   :END:

   [2020-08-12 Ср]

** TASK Сделать комментарии модулям и функциям
   :PROPERTIES:
   :issue_id: 23
   :issue_type: task
   :END:

   [2020-08-12 Ср]

** TASK Перевести все объявления переменных из var в const
   :PROPERTIES:
   :issue_id: 24
   :issue_type: task
   :END:

   [2020-08-12 Ср]
